{
 "title": "Yakle Kafka Overview",
 "description": "Dashboard for yakle consumer group metrics.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "consumer_group",
    "label": "Consumer Group",
    "query": "label_values(yakle_group_topic_partition_current_offset, group)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(yakle_group_topic_partition_current_offset, topic)"
   }
  ]
 },
 "panels": [
  { "title": "Group Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Topic Offset Lag Avg",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(yakle_group_topic_partition_offset_lag{group=\"$consumer_group\", topic=\"$topic\"})"
    }
   ]
  },
  {
   "title": "$consumer_group  / $topic Offset Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Messages" }
   ],
   "targets": [
    {
     "expr": "avg by (group, topic) (yakle_group_topic_partition_offset_lag{group=\"$consumer_group\", topic=\"$topic\"})",
     "legendFormat": "avg"
    },
    {
     "expr": "max by (group, topic) (yakle_group_topic_partition_offset_lag{group=\"$consumer_group\", topic=\"$topic\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum(yakle_group_topic_partition_offset_lag{group=\"$consumer_group\", topic=\"$topic\"})",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "Offset Lag per partition",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Messages" }
   ],
   "targets": [
    {
     "expr": "avg by (partition) (yakle_group_topic_partition_offset_lag{group=\"$consumer_group\", topic=\"$topic\"})",
     "legendFormat": "Partiton {{partition}}"
    }
   ]
  },
  {
   "title": "Topic Time Lag Avg",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(yakle_group_topic_partition_time_lag{group=\"$consumer_group\", topic=\"$topic\"}) /1000"
    }
   ]
  },
  {
   "title": "Topic Commit Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg (sum(rate(yakle_group_topic_partition_current_offset{group=\"$consumer_group\", topic=\"$topic\"}[2m])))"
    }
   ]
  },
  {
   "title": "$consumer_group  / $topic Time Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "ms", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "avg(yakle_group_topic_partition_time_lag{group=\"$consumer_group\", topic=\"$topic\"})",
     "legendFormat": "avg"
    },
    {
     "expr": "max(yakle_group_topic_partition_time_lag{group=\"$consumer_group\", topic=\"$topic\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "$consumer_group Commit Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "pps", "label": "Msg/s" }
   ],
   "targets": [
    {
     "expr": "avg (sum(rate(yakle_topic_partition_newest_offset{topic=\"$topic\"}[4m])))",
     "legendFormat": "in"
    },
    {
     "expr": "avg (sum(rate(yakle_group_topic_partition_current_offset{group=\"$consumer_group\", topic=\"$topic\"}[4m])))",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Oldest Message Time",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "min(yakle_topic_partition_oldest_time{topic=\"$topic\"})/1000"
    }
   ]
  }
 ]
}