{
 "title": "Kafka - Cluster Overview (yakle exporter)",
 "description": "Cluster wide metrics exported by yakle",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "highThroughputTopics",
    "query": {
     "query": "query_result(topk(15, avg by (topic) (avg_over_time(kafka_topic_partition_newest_offset{cluster=\"$cluster\"}[${__range_s}s]))))"
    }
   },
   {
    "name": "topOffsetCommitters",
    "query": {
     "query": "query_result(topk(5, avg by (group) (avg_over_time(kafka_group_topic_partition_current_offset{cluster=\"$cluster\"}[${__range_s}s]))))"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kafka_cluster_info, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Messages in/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_newest_offset{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "message/s"
    }
   ]
  },
  {
   "title": "Brokers Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_cluster_info{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Not Preferred Leader",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_not_preferred{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Offset commits processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(kafka_group_topic_partition_current_offset{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_info{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_under_replicated{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Messages in/sec by topic [Top 15]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_topic_partition_newest_offset{cluster=\"$cluster\", topic=~\"$highThroughputTopics\"}[$__rate_interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Top Offset Committers [Top 5]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (group) (rate(kafka_group_topic_partition_current_offset{cluster=\"$cluster\", group=~\"$topOffsetCommitters\"}[$__rate_interval]))",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Log Dir Size by Broker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (broker) (kafka_topic_broker_logdir_size{cluster=\"$cluster\"})",
     "legendFormat": "Broker {{broker}}"
    }
   ]
  },
  {
   "title": "Brokers",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "kafka_broker_info{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Topics Info",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "kafka_topic_info{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Groups Info",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "kafka_group_info{cluster=\"$cluster\"}"
    }
   ]
  }
 ]
}