{
 "title": "Kafka - ConsumerGroup Overview (yakle exporter)",
 "description": "Kafka Topic metrics exported by yakle",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kafka_cluster_info, cluster)"
    }
   },
   {
    "name": "consumerGroup",
    "label": "Consumer Group",
    "query": {
     "query": "label_values(kafka_group_topic_partition_offset_lag{cluster=\"$cluster\"}, group)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_group_topic_partition_offset_lag{cluster=\"$cluster\",group=\"$consumerGroup\"}, topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Consumergroup => Topic Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (group,topic) (kafka_group_topic_partition_offset_lag{cluster=\"$cluster\", group=\"$consumerGroup\", topic=\"$topic\"})",
     "legendFormat": "{{group}} => {{topic}}"
    }
   ]
  },
  {
   "title": "Offset Commit Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (sum(rate(kafka_group_topic_partition_current_offset{cluster=\"$cluster\", group=\"$consumerGroup\"}[3m])))"
    }
   ]
  },
  {
   "title": "Topic Lag",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (group,topic) (kafka_group_topic_partition_offset_lag{cluster=\"$cluster\", group=\"$consumerGroup\", topic=\"$topic\"})"
    }
   ]
  },
  {
   "title": "Messages In vs Consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_topic_partition_newest_offset{cluster=\"$cluster\",topic=\"$topic\"}[$__rate_interval]))",
     "legendFormat": "Incoming: {{topic}}"
    },
    {
     "expr": "sum by (topic, group) (rate(kafka_group_topic_partition_current_offset{cluster=\"$cluster\", group=\"$consumerGroup\", topic=\"$topic\"}[$__rate_interval]))",
     "legendFormat": "Consuming: {{topic}}"
    }
   ]
  }
 ]
}