{
 "title": "Kafka - Topics Overview (yakle exporter)",
 "description": "Kafka Topic metrics exported by yakle",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kafka_cluster_info, cluster)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_topic_partition_newest_offset{cluster=\"$cluster\"}, topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Message count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_newest_offset{cluster=\"$cluster\", topic=\"$topic\"}) - sum(kafka_topic_partition_oldest_offset{cluster=\"$cluster\", topic=\"$topic\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Partition Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_topic_info{cluster=\"$cluster\", topic=\"$topic\"}"
    }
   ]
  },
  {
   "title": "Messages in/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_newest_offset{cluster=\"$cluster\", topic=\"$topic\"}[$__rate_interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Replication Factor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_topic_info{cluster=\"$cluster\", topic=\"$topic\"}"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "avg by (partition) (kafka_topic_partition_oldest_offset{cluster=\"$cluster\", topic=\"$topic\"})"
    },
    {
     "expr": "avg by (partition) (kafka_topic_partition_newest_offset{cluster=\"$cluster\", topic=\"$topic\"})"
    }
   ]
  },
  {
   "title": "Total Log Dir Size WIP",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (topic) (kafka_topic_broker_logdir_size{cluster=\"$cluster\", topic=\"$topic\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Subscribed Consumer Groups",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "kafka_group_topic_partition_offset_lag{cluster=\"$cluster\", topic=\"$topic\"}"
    }
   ]
  }
 ]
}